/**
 * Global Visa Database
 * ─────────────────────────────────────────────────────────────────────────────
 * Authoritative data source for all visa requirements.
 * Structured as relational records — drop-in replaceable with a real DB query.
 *
 * Sources: Official embassy/consulate websites, Schengen Visa Code,
 * US Dept. of State, UK Home Office, UAE ICP, Saudi MOFA.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { CountryVisaProfile, VisaDocument, VisaType } from "./visa-types";

// ─── Master Document Registry ─────────────────────────────────────────────────
// Each document defined once; visa types reference them by id.

export const DOCUMENT_REGISTRY: Record<string, VisaDocument> = {
  passport: {
    id: "passport",
    label: "Valid Passport",
    description: "Original passport with at least 6 months validity beyond your travel dates and 2 blank pages.",
    icon: "badge",
    required: true,
    allowedTypes: ["pdf", "jpg", "jpeg", "png"],
    maxSizeMB: 5,
    notes: "Passports expiring within 6 months of travel will be rejected.",
  },
  passport_copy: {
    id: "passport_copy",
    label: "Passport Copy (All Pages)",
    description: "Colour scan of the passport biodata page and all previously stamped pages.",
    icon: "content_copy",
    required: true,
    allowedTypes: ["pdf", "jpg", "jpeg", "png"],
    maxSizeMB: 10,
    multiple: true,
  },
  photo: {
    id: "photo",
    label: "Passport Photo",
    description: "Recent passport-size photograph (3.5×4.5 cm) against a plain white background, taken within 6 months.",
    icon: "photo_camera",
    required: true,
    allowedTypes: ["jpg", "jpeg", "png"],
    maxSizeMB: 2,
    notes: "Digital photos must be at least 600×750 px, no glasses or head coverings (unless religious).",
  },
  application_form: {
    id: "application_form",
    label: "Completed Application Form",
    description: "Signed visa application form provided by the embassy or our team.",
    icon: "description",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  bank_statement: {
    id: "bank_statement",
    label: "Bank Statement (3–6 months)",
    description: "Original bank statements for the last 3–6 months showing sufficient funds for the trip.",
    icon: "account_balance_wallet",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
    notes: "Must be stamped and signed by the bank. Digital bank exports may not be accepted.",
  },
  hotel_reservation: {
    id: "hotel_reservation",
    label: "Hotel Reservation",
    description: "Confirmed hotel booking or accommodation proof for the entire stay. Must include check-in/check-out dates.",
    icon: "hotel",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  flight_itinerary: {
    id: "flight_itinerary",
    label: "Flight Itinerary",
    description: "Round-trip or multi-city flight booking confirmation. Does not need to be a paid ticket — an itinerary from us is accepted.",
    icon: "airplane_ticket",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  travel_insurance: {
    id: "travel_insurance",
    label: "Travel Insurance",
    description: "Travel medical insurance certificate covering the entire stay with a minimum coverage of €30,000 / $50,000.",
    icon: "health_and_safety",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
    notes: "Schengen requires minimum €30,000 coverage valid in all Schengen member states.",
  },
  employment_letter: {
    id: "employment_letter",
    label: "Employment Letter / NOC",
    description: "Official letter from your employer confirming your position, salary, and approved leave for the travel period.",
    icon: "work",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
    notes: "Must be on company letterhead, signed by HR or management, and include contact details.",
  },
  invitation_letter: {
    id: "invitation_letter",
    label: "Invitation Letter",
    description: "Official letter of invitation from your host (person or company) in the destination country.",
    icon: "mail",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  sponsor_letter: {
    id: "sponsor_letter",
    label: "Sponsor Declaration Letter",
    description: "A notarized letter from your sponsor confirming financial responsibility for your stay.",
    icon: "support_agent",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  marriage_certificate: {
    id: "marriage_certificate",
    label: "Marriage Certificate",
    description: "Certified copy of marriage certificate, with official translation if not in English or the destination language.",
    icon: "favorite",
    required: false,
    allowedTypes: ["pdf", "jpg", "jpeg"],
    maxSizeMB: 5,
    notes: "Required for spouse/family visas. Must be attested/apostilled.",
  },
  birth_certificate: {
    id: "birth_certificate",
    label: "Birth Certificate",
    description: "Certified birth certificate for all applicants under 18, or when adding dependents.",
    icon: "child_care",
    required: false,
    allowedTypes: ["pdf", "jpg", "jpeg"],
    maxSizeMB: 5,
  },
  national_id: {
    id: "national_id",
    label: "National ID Card",
    description: "Valid national identity card (front and back).",
    icon: "contact_page",
    required: false,
    allowedTypes: ["pdf", "jpg", "jpeg", "png"],
    maxSizeMB: 3,
  },
  residence_permit: {
    id: "residence_permit",
    label: "Residence Permit",
    description: "Current residence permit if you are not a citizen of your country of application.",
    icon: "home",
    required: false,
    allowedTypes: ["pdf", "jpg", "jpeg"],
    maxSizeMB: 5,
  },
  police_clearance: {
    id: "police_clearance",
    label: "Police Clearance Certificate",
    description: "Official criminal background check from your country of residence, issued within the last 6 months.",
    icon: "gavel",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
    notes: "Must be attested by the relevant ministry of foreign affairs.",
  },
  medical_report: {
    id: "medical_report",
    label: "Medical Examination Report",
    description: "Medical fitness certificate from an approved physician, including vaccinations.",
    icon: "local_hospital",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
  },
  university_acceptance: {
    id: "university_acceptance",
    label: "University / School Acceptance Letter",
    description: "Official acceptance letter from your institution confirming enrollment, course details, and duration.",
    icon: "school",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  university_transcripts: {
    id: "university_transcripts",
    label: "Academic Transcripts",
    description: "Official academic transcripts from your previous institution.",
    icon: "grading",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
    multiple: true,
  },
  tuition_proof: {
    id: "tuition_proof",
    label: "Tuition Payment Receipt / Scholarship Letter",
    description: "Evidence of tuition payment or scholarship award for the study period.",
    icon: "receipt_long",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  company_registration: {
    id: "company_registration",
    label: "Company Registration Documents",
    description: "Certified company registration certificate (commercial register extract).",
    icon: "domain",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
  },
  tax_returns: {
    id: "tax_returns",
    label: "Income Tax Returns (2 years)",
    description: "Last 2 years personal or business income tax returns.",
    icon: "calculate",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
    multiple: true,
  },
  business_letter: {
    id: "business_letter",
    label: "Business Letter / Conference Invitation",
    description: "Official business letter from your company or conference organizer outlining purpose and duration of the visit.",
    icon: "business_center",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  proof_of_accommodation: {
    id: "proof_of_accommodation",
    label: "Proof of Accommodation",
    description: "Evidence of accommodation arrangements — hotel booking, host's address, or company-provided housing details.",
    icon: "house",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  hajj_umrah_permit: {
    id: "hajj_umrah_permit",
    label: "Hajj / Umrah Package Booking",
    description: "Confirmed Hajj or Umrah package from an authorized travel agency, including accommodation in Makkah and Madinah.",
    icon: "mosque",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  return_ticket: {
    id: "return_ticket",
    label: "Return Ticket Confirmation",
    description: "Confirmed return flight ticket showing departure from the destination country.",
    icon: "confirmation_number",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  work_contract: {
    id: "work_contract",
    label: "Work Contract / Job Offer Letter",
    description: "Signed employment contract or job offer letter from the employer in the destination country.",
    icon: "assignment",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  labor_condition: {
    id: "labor_condition",
    label: "Labor Condition Application (LCA)",
    description: "Approved I-129 Petition and Labor Condition Application filed by the US employer.",
    icon: "approval",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
  },
  i20_form: {
    id: "i20_form",
    label: "Form I-20 (SEVIS)",
    description: "Certificate of Eligibility for Nonimmigrant Student Status issued by your US institution.",
    icon: "school",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  ds160_form: {
    id: "ds160_form",
    label: "DS-160 Confirmation Page",
    description: "Printed confirmation page of your completed DS-160 Nonimmigrant Visa Application.",
    icon: "task_alt",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 2,
  },
  sevis_receipt: {
    id: "sevis_receipt",
    label: "SEVIS Fee Payment Receipt",
    description: "I-901 SEVIS fee payment receipt.",
    icon: "receipt",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 2,
  },
  cas_number: {
    id: "cas_number",
    label: "CAS (Confirmation of Acceptance for Studies)",
    description: "Unique CAS reference number issued by your UK university via UKVI.",
    icon: "key",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 2,
  },
  english_proficiency: {
    id: "english_proficiency",
    label: "English Proficiency Certificate (IELTS/TOEFL)",
    description: "Official IELTS, TOEFL, or equivalent English language test result meeting the institution's requirements.",
    icon: "translate",
    required: true,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  sponsor_host_id: {
    id: "sponsor_host_id",
    label: "Host / Sponsor ID Copy",
    description: "Copy of the national ID or residence permit of your host or sponsor in the destination country.",
    icon: "person",
    required: false,
    allowedTypes: ["pdf", "jpg", "jpeg"],
    maxSizeMB: 3,
  },
  proof_of_relationship: {
    id: "proof_of_relationship",
    label: "Proof of Relationship",
    description: "Documents proving your relationship with the inviting party (e.g. marriage certificate, family records).",
    icon: "group",
    required: true,
    allowedTypes: ["pdf", "jpg", "jpeg"],
    maxSizeMB: 10,
    multiple: true,
  },
  financial_guarantee: {
    id: "financial_guarantee",
    label: "Financial Guarantee Letter",
    description: "Notarized letter from a sponsor or guarantor confirming financial support for the applicant's stay.",
    icon: "verified",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  no_objection_certificate: {
    id: "no_objection_certificate",
    label: "No Objection Certificate (NOC)",
    description: "NOC from your employer, school, or government authority confirming you are permitted to travel.",
    icon: "check_circle",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  trade_license: {
    id: "trade_license",
    label: "Trade License / Business License",
    description: "Valid trade or business license for self-employed applicants.",
    icon: "store",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 5,
  },
  property_ownership: {
    id: "property_ownership",
    label: "Property Ownership Documents",
    description: "Title deeds or mortgage statement as evidence of ties to your home country.",
    icon: "real_estate_agent",
    required: false,
    allowedTypes: ["pdf"],
    maxSizeMB: 10,
    multiple: true,
  },
  vaccination_certificate: {
    id: "vaccination_certificate",
    label: "Vaccination Certificate",
    description: "Official vaccination certificate for required vaccinations (e.g. Yellow Fever, COVID-19 per destination).",
    icon: "vaccines",
    required: false,
    allowedTypes: ["pdf", "jpg"],
    maxSizeMB: 3,
  },
};

// ─── Helper: Build document array from ids ────────────────────────────────────

function docs(ids: string[], overrides: Partial<VisaDocument>[] = []): VisaDocument[] {
  return ids.map((id, i) => ({
    ...DOCUMENT_REGISTRY[id],
    ...(overrides[i] ?? {}),
  }));
}

// ─── Shared Document Bundles ──────────────────────────────────────────────────

const TOURIST_CORE = [
  "passport", "passport_copy", "photo", "application_form",
  "bank_statement", "hotel_reservation", "flight_itinerary",
  "travel_insurance", "employment_letter",
];

const SCHENGEN_TOURIST_DOCS = docs([
  ...TOURIST_CORE, "return_ticket", "no_objection_certificate",
]);

const SCHENGEN_BUSINESS_DOCS = docs([
  "passport", "passport_copy", "photo", "application_form",
  "bank_statement", "flight_itinerary", "travel_insurance",
  "business_letter", "company_registration", "hotel_reservation",
  "employment_letter",
]);

const SCHENGEN_STUDENT_DOCS = docs([
  "passport", "passport_copy", "photo", "application_form",
  "bank_statement", "university_acceptance", "tuition_proof",
  "travel_insurance", "flight_itinerary", "english_proficiency",
  "accommodation", "no_objection_certificate",
].filter(Boolean));

const SCHENGEN_FAMILY_DOCS = docs([
  "passport", "passport_copy", "photo", "application_form",
  "bank_statement", "flight_itinerary", "travel_insurance",
  "marriage_certificate", "birth_certificate", "sponsor_letter",
  "sponsor_host_id", "proof_of_relationship",
]);

// ─── Visa Type Builders ───────────────────────────────────────────────────────

function schengenTypes(countryName: string): VisaType[] {
  return [
    {
      id: "tourist",
      label: "Tourist / Leisure Visa",
      description: `Short-stay visa for tourism, sightseeing, and leisure in ${countryName} and the Schengen Area.`,
      icon: "luggage",
      processingTime: "15 working days",
      governmentFee: "€80 / €160 (rush)",
      maxStay: "90 days in any 180-day period",
      validity: "Single / Multiple entry",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: SCHENGEN_TOURIST_DOCS,
    },
    {
      id: "business",
      label: "Business Visa",
      description: `For attending conferences, meetings, negotiations, or business activities in ${countryName}.`,
      icon: "business_center",
      processingTime: "15 working days",
      governmentFee: "€80",
      maxStay: "90 days in any 180-day period",
      validity: "Single / Multiple entry",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: SCHENGEN_BUSINESS_DOCS,
    },
    {
      id: "student",
      label: "Student Visa",
      description: `For studying at a ${countryName} educational institution. Allows work up to 20 hrs/week in most Schengen states.`,
      icon: "school",
      processingTime: "15–30 working days",
      governmentFee: "€80",
      maxStay: "Duration of course",
      validity: "Single / Multiple entry",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: SCHENGEN_STUDENT_DOCS,
    },
    {
      id: "family_visit",
      label: "Family Visit Visa",
      description: `For visiting immediate family members who are citizens or legal residents of ${countryName}.`,
      icon: "family_restroom",
      processingTime: "15 working days",
      governmentFee: "€80 (children under 6: free)",
      maxStay: "90 days",
      validity: "Single / Multiple entry",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: SCHENGEN_FAMILY_DOCS,
    },
    {
      id: "medical",
      label: "Medical Visa",
      description: `For seeking medical treatment in ${countryName}. Requires confirmation from a licensed medical institution.`,
      icon: "local_hospital",
      processingTime: "10 working days (priority)",
      governmentFee: "€80",
      maxStay: "Duration of treatment",
      validity: "Single entry",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: docs([
        "passport", "passport_copy", "photo", "application_form",
        "bank_statement", "travel_insurance", "medical_report",
        "flight_itinerary", "proof_of_accommodation",
      ]),
    },
    {
      id: "transit",
      label: "Airport Transit Visa",
      description: `Required for transiting through ${countryName} without entering the Schengen zone.`,
      icon: "connecting_airports",
      processingTime: "5–10 working days",
      governmentFee: "€80",
      maxStay: "Not applicable (transit only)",
      validity: "Single transit",
      eVisa: false,
      visaOnArrival: false,
      requiredDocuments: docs([
        "passport", "passport_copy", "photo", "application_form",
        "flight_itinerary",
      ]),
    },
  ];
}

// ─── Country Database ─────────────────────────────────────────────────────────

export const VISA_DATABASE: CountryVisaProfile[] = [

  // ─── UNITED STATES ──────────────────────────────────────────────────────────
  {
    countryCode: "US",
    countryName: "United States",
    flag: "🇺🇸",
    continent: "North America",
    capital: "Washington, D.C.",
    currency: "USD",
    embassyUrl: "https://eg.usembassy.gov",
    visaTypes: [
      {
        id: "b1_b2",
        label: "B1/B2 Visitor Visa",
        description: "The most common US visa. B1 is for business; B2 is for tourism, vacation, or medical treatment. Usually issued together.",
        icon: "travel_explore",
        processingTime: "Varies — interview appointment wait times can be 3–18 months",
        governmentFee: "$185 (non-refundable MRV fee)",
        maxStay: "Up to 6 months (determined by CBP at entry)",
        validity: "Up to 10 years, multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "bank_statement",
          "employment_letter", "no_objection_certificate",
          "property_ownership", "return_ticket",
        ]),
      },
      {
        id: "f1",
        label: "F1 Student Visa",
        description: "For full-time academic study at a US college, university, seminary, conservatory, academic high school, or private elementary school.",
        icon: "school",
        processingTime: "2–5 weeks after interview",
        governmentFee: "$185 MRV + $350 SEVIS fee",
        maxStay: "Duration of Status (D/S)",
        validity: "Single or multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "i20_form",
          "sevis_receipt", "bank_statement", "university_acceptance",
          "university_transcripts", "english_proficiency",
          "no_objection_certificate",
        ]),
      },
      {
        id: "j1",
        label: "J1 Exchange Visitor Visa",
        description: "For participants in exchange visitor programs including au pairs, camp counselors, research scholars, and summer work travel.",
        icon: "swap_horiz",
        processingTime: "2–5 weeks",
        governmentFee: "$185 MRV",
        maxStay: "Duration of program",
        validity: "Single or multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "sevis_receipt",
          "bank_statement", "employment_letter", "university_acceptance",
        ]),
      },
      {
        id: "h1b",
        label: "H1B Specialty Occupation Visa",
        description: "For specialty occupation workers sponsored by a US employer. Subject to annual cap and lottery.",
        icon: "engineering",
        processingTime: "3–6 months (standard) / 2–3 weeks (premium processing)",
        governmentFee: "$730–$6,460 (employer-paid)",
        maxStay: "3 years (extendable to 6 years)",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "labor_condition",
          "work_contract", "university_transcripts", "police_clearance",
        ]),
      },
      {
        id: "l1",
        label: "L1 Intracompany Transfer Visa",
        description: "For managers, executives, or specialized knowledge employees transferring from a foreign office to a US office of the same company.",
        icon: "swap_horiz",
        processingTime: "2–6 months",
        governmentFee: "$460–$960",
        maxStay: "3 years (L1A up to 7 years)",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "work_contract",
          "company_registration", "employment_letter",
          "tax_returns", "police_clearance",
        ]),
      },
      {
        id: "o1",
        label: "O1 Extraordinary Ability Visa",
        description: "For individuals with extraordinary ability in sciences, arts, education, business, or athletics.",
        icon: "star",
        processingTime: "2–6 months",
        governmentFee: "$460",
        maxStay: "3 years (extendable)",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "ds160_form", "work_contract",
          "employment_letter", "police_clearance",
        ]),
      },
    ],
  },

  // ─── UNITED KINGDOM ─────────────────────────────────────────────────────────
  {
    countryCode: "GB",
    countryName: "United Kingdom",
    flag: "🇬🇧",
    continent: "Europe",
    capital: "London",
    currency: "GBP",
    embassyUrl: "https://www.gov.uk/browse/visas-immigration",
    visaTypes: [
      {
        id: "standard_visitor",
        label: "Standard Visitor Visa",
        description: "For tourism, family visits, short business trips, or medical treatment in the UK.",
        icon: "luggage",
        processingTime: "3 weeks (standard) / 5 working days (priority)",
        governmentFee: "£115 (standard) / £500 (priority)",
        maxStay: "Up to 6 months",
        validity: "Up to 10 years, multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "bank_statement",
          "employment_letter", "hotel_reservation", "flight_itinerary",
          "return_ticket", "no_objection_certificate",
        ]),
      },
      {
        id: "student",
        label: "Student Visa (Tier 4)",
        description: "For students aged 16+ accepted onto a full-time course at a UK Higher Education Institution.",
        icon: "school",
        processingTime: "3 weeks (standard) / 5 working days (priority)",
        governmentFee: "£490 (outside UK) + £776/year Immigration Health Surcharge",
        maxStay: "Duration of course + 4 months",
        validity: "Per course duration",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "cas_number",
          "bank_statement", "university_acceptance", "english_proficiency",
          "university_transcripts", "tuition_proof",
          "no_objection_certificate",
        ]),
      },
      {
        id: "skilled_worker",
        label: "Skilled Worker Visa",
        description: "For workers who have a job offer from a UK employer with a sponsor licence.",
        icon: "engineering",
        processingTime: "3 weeks",
        governmentFee: "£625–£1,423 + Immigration Health Surcharge",
        maxStay: "Up to 5 years",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "work_contract",
          "employment_letter", "english_proficiency",
          "police_clearance", "bank_statement", "medical_report",
        ]),
      },
      {
        id: "family",
        label: "Family Visa (Spouse / Dependent)",
        description: "To join a family member who is settled in the UK or has limited leave to remain.",
        icon: "family_restroom",
        processingTime: "24 weeks (standard) / 12 weeks (priority)",
        governmentFee: "£1,846",
        maxStay: "33 months initially",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "marriage_certificate", "birth_certificate",
          "proof_of_relationship", "bank_statement",
          "sponsor_host_id", "english_proficiency",
        ]),
      },
    ],
  },

  // ─── SCHENGEN: GERMANY ──────────────────────────────────────────────────────
  {
    countryCode: "DE",
    countryName: "Germany",
    flag: "🇩🇪",
    continent: "Europe",
    capital: "Berlin",
    currency: "EUR",
    embassyUrl: "https://cairo.diplo.de/eg-ar/visa",
    visaTypes: schengenTypes("Germany"),
  },

  // ─── SCHENGEN: FRANCE ───────────────────────────────────────────────────────
  {
    countryCode: "FR",
    countryName: "France",
    flag: "🇫🇷",
    continent: "Europe",
    capital: "Paris",
    currency: "EUR",
    embassyUrl: "https://eg.ambafrance.org",
    visaTypes: schengenTypes("France"),
  },

  // ─── SCHENGEN: ITALY ────────────────────────────────────────────────────────
  {
    countryCode: "IT",
    countryName: "Italy",
    flag: "🇮🇹",
    continent: "Europe",
    capital: "Rome",
    currency: "EUR",
    embassyUrl: "https://ambilcairo.esteri.it",
    visaTypes: schengenTypes("Italy"),
  },

  // ─── SCHENGEN: SPAIN ────────────────────────────────────────────────────────
  {
    countryCode: "ES",
    countryName: "Spain",
    flag: "🇪🇸",
    continent: "Europe",
    capital: "Madrid",
    currency: "EUR",
    embassyUrl: "https://www.exteriores.gob.es/embajadas/elcairo",
    visaTypes: schengenTypes("Spain"),
  },

  // ─── SCHENGEN: NETHERLANDS ─────────────────────────────────────────────────
  {
    countryCode: "NL",
    countryName: "Netherlands",
    flag: "🇳🇱",
    continent: "Europe",
    capital: "Amsterdam",
    currency: "EUR",
    embassyUrl: "https://www.netherlandsworldwide.nl/countries/egypt",
    visaTypes: schengenTypes("Netherlands"),
  },

  // ─── SCHENGEN: SWITZERLAND ─────────────────────────────────────────────────
  {
    countryCode: "CH",
    countryName: "Switzerland",
    flag: "🇨🇭",
    continent: "Europe",
    capital: "Bern",
    currency: "CHF",
    embassyUrl: "https://www.eda.admin.ch/cairo",
    visaTypes: schengenTypes("Switzerland"),
  },

  // ─── SCHENGEN: AUSTRIA ─────────────────────────────────────────────────────
  {
    countryCode: "AT",
    countryName: "Austria",
    flag: "🇦🇹",
    continent: "Europe",
    capital: "Vienna",
    currency: "EUR",
    embassyUrl: "https://www.bmeia.gv.at/botschaft/kairo",
    visaTypes: schengenTypes("Austria"),
  },

  // ─── SCHENGEN: GREECE ──────────────────────────────────────────────────────
  {
    countryCode: "GR",
    countryName: "Greece",
    flag: "🇬🇷",
    continent: "Europe",
    capital: "Athens",
    currency: "EUR",
    embassyUrl: "https://www.mfa.gr/cairo",
    visaTypes: schengenTypes("Greece"),
  },

  // ─── SCHENGEN: PORTUGAL ────────────────────────────────────────────────────
  {
    countryCode: "PT",
    countryName: "Portugal",
    flag: "🇵🇹",
    continent: "Europe",
    capital: "Lisbon",
    currency: "EUR",
    visaTypes: schengenTypes("Portugal"),
  },

  // ─── SCHENGEN: SWEDEN ──────────────────────────────────────────────────────
  {
    countryCode: "SE",
    countryName: "Sweden",
    flag: "🇸🇪",
    continent: "Europe",
    capital: "Stockholm",
    currency: "SEK",
    visaTypes: schengenTypes("Sweden"),
  },

  // ─── SCHENGEN: NORWAY ──────────────────────────────────────────────────────
  {
    countryCode: "NO",
    countryName: "Norway",
    flag: "🇳🇴",
    continent: "Europe",
    capital: "Oslo",
    currency: "NOK",
    visaTypes: schengenTypes("Norway"),
  },

  // ─── UAE ────────────────────────────────────────────────────────────────────
  {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    flag: "🇦🇪",
    continent: "Asia",
    capital: "Abu Dhabi",
    currency: "AED",
    embassyUrl: "https://www.mofaic.gov.ae",
    visaFreeForEgyptian: false,
    visaTypes: [
      {
        id: "tourist_30",
        label: "Tourist Visa (30 Days)",
        description: "e-Visa for tourism. Can be extended once for another 30 days.",
        icon: "luggage",
        processingTime: "3–5 business days",
        governmentFee: "AED 250 + AED 100 service",
        maxStay: "30 days",
        validity: "60 days from issue",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "travel_insurance",
        ]),
      },
      {
        id: "tourist_60",
        label: "Tourist Visa (60 Days)",
        description: "e-Visa for longer leisure visits to the UAE.",
        icon: "luggage",
        processingTime: "3–5 business days",
        governmentFee: "AED 500 + AED 100 service",
        maxStay: "60 days",
        validity: "90 days from issue",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "travel_insurance",
        ]),
      },
      {
        id: "visit",
        label: "Visit Visa (Family / Friends)",
        description: "Sponsored by a UAE resident or family member for visiting purposes.",
        icon: "family_restroom",
        processingTime: "3–5 business days",
        governmentFee: "AED 300–500",
        maxStay: "30–90 days",
        validity: "Per approval",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "sponsor_letter", "sponsor_host_id", "bank_statement",
          "proof_of_relationship",
        ]),
      },
      {
        id: "employment",
        label: "Employment / Residence Visa",
        description: "Sponsored by a UAE employer. Allows working and residing in the UAE.",
        icon: "work",
        processingTime: "2–4 weeks",
        governmentFee: "AED 500–1,500",
        maxStay: "2–3 years (renewable)",
        validity: "Per labor contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts",
        ]),
      },
      {
        id: "transit",
        label: "Transit Visa (96 Hours)",
        description: "Short transit visa for travelers connecting through UAE airports.",
        icon: "connecting_airports",
        processingTime: "1–2 business days",
        governmentFee: "AED 50",
        maxStay: "96 hours",
        validity: "Per approval",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "flight_itinerary",
        ]),
      },
    ],
  },

  // ─── SAUDI ARABIA ───────────────────────────────────────────────────────────
  {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    flag: "🇸🇦",
    continent: "Asia",
    capital: "Riyadh",
    currency: "SAR",
    embassyUrl: "https://www.mofa.gov.sa",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist e-Visa",
        description: "Online tourist visa for leisure travel. Valid for 1 year with multiple entries, max 90 days per visit.",
        icon: "luggage",
        processingTime: "Instant – 24 hours (online)",
        governmentFee: "SAR 300 (~$80)",
        maxStay: "90 days per visit",
        validity: "1 year, multiple entry",
        eVisa: true,
        visaOnArrival: true,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "travel_insurance",
          "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "business",
        label: "Business Visa",
        description: "For business meetings, conferences, and commercial activities in Saudi Arabia.",
        icon: "business_center",
        processingTime: "5–10 business days",
        governmentFee: "SAR 500",
        maxStay: "90 days",
        validity: "1 year, multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "business_letter", "company_registration",
          "bank_statement", "invitation_letter",
          "employment_letter", "return_ticket",
        ]),
      },
      {
        id: "umrah",
        label: "Umrah Visa",
        description: "For Muslims performing the Umrah pilgrimage. Must be booked through an authorized Umrah service provider.",
        icon: "mosque",
        processingTime: "3–7 business days",
        governmentFee: "SAR 300",
        maxStay: "30 days",
        validity: "Per booking",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "hajj_umrah_permit", "vaccination_certificate",
          "return_ticket", "bank_statement",
          "marriage_certificate", // for women travelling with spouse
        ]),
      },
      {
        id: "hajj",
        label: "Hajj Visa",
        description: "For Muslims performing the obligatory Hajj pilgrimage. Issued through official national Hajj missions only.",
        icon: "mosque",
        processingTime: "Allocated through Hajj mission",
        governmentFee: "Via authorized agency",
        maxStay: "40 days",
        validity: "Season-specific",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "hajj_umrah_permit", "vaccination_certificate",
          "bank_statement", "marriage_certificate",
          "no_objection_certificate",
        ]),
      },
      {
        id: "work",
        label: "Work Visa (Iqama)",
        description: "Work residence permit (Iqama) sponsored by a Saudi employer. Includes entry visa and work authorization.",
        icon: "work",
        processingTime: "4–8 weeks",
        governmentFee: "SAR 2,000+",
        maxStay: "1–2 years (renewable)",
        validity: "Per labor contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts", "vaccination_certificate",
        ]),
      },
    ],
  },

  // ─── CHINA ──────────────────────────────────────────────────────────────────
  {
    countryCode: "CN",
    countryName: "China",
    flag: "🇨🇳",
    continent: "Asia",
    capital: "Beijing",
    currency: "CNY",
    embassyUrl: "https://eg.china-embassy.gov.cn",
    visaTypes: [
      {
        id: "l_tourist",
        label: "L — Tourist Visa",
        description: "For individual or group tourism in China. China also offers 144-hour visa-free transit in select cities.",
        icon: "luggage",
        processingTime: "4 business days (standard) / 2–3 days (express)",
        governmentFee: "$140 / CNY 1,000",
        maxStay: "30–90 days",
        validity: "Single / Double / Multiple",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "hotel_reservation", "flight_itinerary",
          "return_ticket", "employment_letter",
        ]),
      },
      {
        id: "m_business",
        label: "M — Business Visa",
        description: "For commercial and trade activities in China.",
        icon: "business_center",
        processingTime: "4 business days",
        governmentFee: "$140",
        maxStay: "30–90 days per visit",
        validity: "Up to 2 years, multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "business_letter", "invitation_letter", "company_registration",
          "bank_statement", "flight_itinerary",
        ]),
      },
      {
        id: "x1_student",
        label: "X1 — Student Visa (6+ months)",
        description: "For students enrolled in full-time courses at Chinese universities lasting more than 6 months.",
        icon: "school",
        processingTime: "4 business days",
        governmentFee: "$140",
        maxStay: "Duration of study",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "university_acceptance", "bank_statement",
          "medical_report", "no_objection_certificate",
        ]),
      },
      {
        id: "z_work",
        label: "Z — Work Visa",
        description: "For foreigners taking up employment in China. Requires a Foreigner's Work Permit from Chinese authorities.",
        icon: "engineering",
        processingTime: "5–10 business days",
        governmentFee: "$140",
        maxStay: "Per contract (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "work_contract", "employment_letter",
          "police_clearance", "medical_report",
          "university_transcripts",
        ]),
      },
      {
        id: "g_transit",
        label: "G — Transit Visa",
        description: "For travelers transiting through China. 144-hour visa-free transit is available in many major cities.",
        icon: "connecting_airports",
        processingTime: "4 business days",
        governmentFee: "$140",
        maxStay: "Per transit",
        validity: "Single transit",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "flight_itinerary",
        ]),
      },
    ],
  },

  // ─── JAPAN ──────────────────────────────────────────────────────────────────
  {
    countryCode: "JP",
    countryName: "Japan",
    flag: "🇯🇵",
    continent: "Asia",
    capital: "Tokyo",
    currency: "JPY",
    embassyUrl: "https://www.eg.emb-japan.go.jp",
    visaTypes: [
      {
        id: "tourist",
        label: "Temporary Visitor Visa (Tourism)",
        description: "For sightseeing, visiting friends/relatives, sports, or recreation in Japan.",
        icon: "luggage",
        processingTime: "5–7 business days",
        governmentFee: "¥3,000 (~$20)",
        maxStay: "90 days",
        validity: "Single / Multiple (3–5 years)",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "employment_letter", "hotel_reservation",
          "flight_itinerary", "return_ticket", "no_objection_certificate",
        ]),
      },
      {
        id: "business",
        label: "Temporary Visitor Visa (Business)",
        description: "For short-term business activities: meetings, conferences, training.",
        icon: "business_center",
        processingTime: "5 business days",
        governmentFee: "¥3,000",
        maxStay: "90 days",
        validity: "Single / Multiple",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "business_letter", "invitation_letter", "company_registration",
          "bank_statement", "employment_letter", "flight_itinerary",
        ]),
      },
      {
        id: "student",
        label: "Student Visa",
        description: "For studying at Japanese universities, language schools, or vocational schools.",
        icon: "school",
        processingTime: "4–8 weeks",
        governmentFee: "¥3,000",
        maxStay: "Duration of enrollment",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "university_acceptance", "bank_statement",
          "english_proficiency", "university_transcripts",
          "no_objection_certificate",
        ]),
      },
      {
        id: "highly_skilled",
        label: "Highly Skilled Professional Visa",
        description: "Point-based immigration system for professionals in academia, advanced business, or R&D.",
        icon: "star",
        processingTime: "2–3 months",
        governmentFee: "¥3,000",
        maxStay: "5 years (renewable)",
        validity: "Renewable",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "work_contract", "employment_letter",
          "university_transcripts", "police_clearance",
          "tax_returns",
        ]),
      },
    ],
  },

  // ─── CANADA ─────────────────────────────────────────────────────────────────
  {
    countryCode: "CA",
    countryName: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    capital: "Ottawa",
    currency: "CAD",
    embassyUrl: "https://www.canada.ca/en/immigration-refugees-citizenship.html",
    visaTypes: [
      {
        id: "visitor",
        label: "Temporary Resident Visa (Visitor Visa)",
        description: "For tourism, visiting family and friends, or short business trips to Canada.",
        icon: "luggage",
        processingTime: "Average 14 days (varies)",
        governmentFee: "CAD 100",
        maxStay: "Up to 6 months",
        validity: "Up to 10 years",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "bank_statement",
          "employment_letter", "return_ticket", "hotel_reservation",
          "no_objection_certificate", "travel_insurance",
          "property_ownership",
        ]),
      },
      {
        id: "student",
        label: "Student Permit",
        description: "For full-time study at a Designated Learning Institution (DLI) in Canada.",
        icon: "school",
        processingTime: "Average 8 weeks",
        governmentFee: "CAD 150",
        maxStay: "Duration of study + 90 days",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "university_acceptance", "bank_statement",
          "english_proficiency", "university_transcripts",
          "no_objection_certificate", "travel_insurance",
        ]),
      },
      {
        id: "work",
        label: "Open / Employer-Specific Work Permit",
        description: "Allows working in Canada, either with a specific employer or with an open permit (PGWP, spousal, etc.).",
        icon: "work",
        processingTime: "6–27 weeks",
        governmentFee: "CAD 155",
        maxStay: "Per permit (up to 2 years)",
        validity: "Per permit",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "bank_statement", "police_clearance",
          "medical_report", "university_transcripts",
        ]),
      },
    ],
  },

  // ─── AUSTRALIA ──────────────────────────────────────────────────────────────
  {
    countryCode: "AU",
    countryName: "Australia",
    flag: "🇦🇺",
    continent: "Oceania",
    capital: "Canberra",
    currency: "AUD",
    embassyUrl: "https://immi.homeaffairs.gov.au",
    visaTypes: [
      {
        id: "tourist_600",
        label: "Visitor Visa (Subclass 600)",
        description: "For tourism, visiting family and friends, or business visitor activities.",
        icon: "luggage",
        processingTime: "25–60 days",
        governmentFee: "AUD 145",
        maxStay: "Up to 12 months",
        validity: "Up to 12 months",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "employment_letter",
          "hotel_reservation", "return_ticket",
          "travel_insurance", "no_objection_certificate",
        ]),
      },
      {
        id: "student_500",
        label: "Student Visa (Subclass 500)",
        description: "For full-time study at an Australian registered provider (CRICOS).",
        icon: "school",
        processingTime: "4–6 weeks",
        governmentFee: "AUD 710",
        maxStay: "Duration of study",
        validity: "Per CoE duration",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "university_acceptance", "bank_statement",
          "english_proficiency", "university_transcripts",
          "health_insurance", "police_clearance",
        ].filter(id => id in DOCUMENT_REGISTRY)).concat(docs(["travel_insurance"])),
      },
      {
        id: "work_482",
        label: "Temporary Skill Shortage Visa (Subclass 482)",
        description: "For skilled workers sponsored by an approved Australian employer.",
        icon: "engineering",
        processingTime: "6–12 months",
        governmentFee: "AUD 1,455",
        maxStay: "2–4 years",
        validity: "Per nomination",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "police_clearance", "medical_report",
          "university_transcripts", "english_proficiency",
        ]),
      },
    ],
  },

  // ─── INDIA ──────────────────────────────────────────────────────────────────
  {
    countryCode: "IN",
    countryName: "India",
    flag: "🇮🇳",
    continent: "Asia",
    capital: "New Delhi",
    currency: "INR",
    embassyUrl: "https://indianvisaonline.gov.in",
    visaTypes: [
      {
        id: "e_tourist",
        label: "e-Visa Tourist",
        description: "Online visa for tourism, recreation, and sightseeing. Available for 30 days, 1 year, or 5 years.",
        icon: "luggage",
        processingTime: "72–96 hours",
        governmentFee: "$25–$80 (varies by nationality)",
        maxStay: "30 days–90 days per visit",
        validity: "30 days / 1 year / 5 years",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "bank_statement",
          "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "e_business",
        label: "e-Visa Business",
        description: "For business meetings, trade, conferences, and setting up business ventures.",
        icon: "business_center",
        processingTime: "72–96 hours",
        governmentFee: "$80",
        maxStay: "90 days per visit",
        validity: "1 year, double entry",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "bank_statement",
          "business_letter", "invitation_letter",
          "company_registration", "return_ticket",
        ]),
      },
      {
        id: "e_medical",
        label: "e-Visa Medical",
        description: "For seeking specialized medical treatment at recognized Indian healthcare facilities.",
        icon: "local_hospital",
        processingTime: "72–96 hours",
        governmentFee: "$25",
        maxStay: "60 days",
        validity: "60 days, triple entry",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "photo", "medical_report",
          "hospital_letter",
        ].filter(id => id in DOCUMENT_REGISTRY)).concat(docs(["bank_statement"])),
      },
    ],
  },

  // ─── TURKEY ─────────────────────────────────────────────────────────────────
  {
    countryCode: "TR",
    countryName: "Turkey",
    flag: "🇹🇷",
    continent: "Asia",
    capital: "Ankara",
    currency: "TRY",
    embassyUrl: "https://evisa.gov.tr",
    visaTypes: [
      {
        id: "e_tourist",
        label: "e-Visa (Tourist / Business)",
        description: "Online single or multiple entry visa for tourism and business. Egyptians can apply online.",
        icon: "luggage",
        processingTime: "24–48 hours",
        governmentFee: "$51.50",
        maxStay: "90 days in any 180-day period",
        validity: "Multiple entry, valid 180 days",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket",
          "hotel_reservation", "employment_letter",
        ]),
      },
      {
        id: "student",
        label: "Student Visa",
        description: "For study at Turkish universities. Apply at the Turkish Embassy for stays over 90 days.",
        icon: "school",
        processingTime: "2–4 weeks",
        governmentFee: "~TRY 2,000",
        maxStay: "Duration of course",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "university_acceptance", "bank_statement",
          "english_proficiency", "no_objection_certificate",
          "travel_insurance",
        ]),
      },
      {
        id: "work",
        label: "Work Permit / Visa",
        description: "For employment in Turkey. The Turkish employer submits the application on behalf of the employee.",
        icon: "work",
        processingTime: "4–8 weeks",
        governmentFee: "~TRY 5,000",
        maxStay: "1–3 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "university_transcripts", "police_clearance",
        ]),
      },
    ],
  },

  // ─── QATAR ──────────────────────────────────────────────────────────────────
  {
    countryCode: "QA",
    countryName: "Qatar",
    flag: "🇶🇦",
    continent: "Asia",
    capital: "Doha",
    currency: "QAR",
    embassyUrl: "https://portal.moi.gov.qa",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa (Online)",
        description: "Visa-on-arrival or online e-visa for Egyptians for tourism in Qatar.",
        icon: "luggage",
        processingTime: "Instant at port of entry",
        governmentFee: "Free (visa on arrival for Egyptians)",
        maxStay: "30 days",
        validity: "Per entry",
        eVisa: true,
        visaOnArrival: true,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "business",
        label: "Business Visa",
        description: "For business meetings, conferences, and trade activities in Qatar.",
        icon: "business_center",
        processingTime: "3–5 business days",
        governmentFee: "QAR 200",
        maxStay: "30 days",
        validity: "Single / Multiple entry",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "business_letter", "invitation_letter",
          "bank_statement", "return_ticket",
        ]),
      },
      {
        id: "work",
        label: "Work / Residence Permit",
        description: "Employment residency permit sponsored by a Qatari employer.",
        icon: "work",
        processingTime: "2–4 weeks",
        governmentFee: "QAR 500",
        maxStay: "2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts",
        ]),
      },
    ],
  },

  // ─── KUWAIT ─────────────────────────────────────────────────────────────────
  {
    countryCode: "KW",
    countryName: "Kuwait",
    flag: "🇰🇼",
    continent: "Asia",
    capital: "Kuwait City",
    currency: "KWD",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist / Visit Visa",
        description: "For tourism or visiting family and friends in Kuwait.",
        icon: "luggage",
        processingTime: "5–10 business days",
        governmentFee: "KWD 3",
        maxStay: "30 days",
        validity: "Single entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "hotel_reservation",
          "return_ticket", "sponsor_letter",
        ]),
      },
      {
        id: "work",
        label: "Work Visa / Residency",
        description: "For employment in Kuwait. Sponsored by a Kuwaiti employer.",
        icon: "work",
        processingTime: "4–6 weeks",
        governmentFee: "KWD 10–50",
        maxStay: "2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts",
        ]),
      },
    ],
  },

  // ─── JORDAN ─────────────────────────────────────────────────────────────────
  {
    countryCode: "JO",
    countryName: "Jordan",
    flag: "🇯🇴",
    continent: "Asia",
    capital: "Amman",
    currency: "JOD",
    embassyUrl: "https://www.mfa.gov.jo",
    visaFreeForEgyptian: true,
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa / Visa on Arrival",
        description: "Egyptians can obtain a visa on arrival at Jordanian ports of entry.",
        icon: "luggage",
        processingTime: "On arrival",
        governmentFee: "JOD 40 (~$56)",
        maxStay: "30 days (extendable)",
        validity: "Single entry",
        eVisa: true,
        visaOnArrival: true,
        requiredDocuments: docs([
          "passport", "photo", "bank_statement",
          "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "work",
        label: "Work Permit",
        description: "Employment work permit sponsored by a Jordanian employer.",
        icon: "work",
        processingTime: "2–4 weeks",
        governmentFee: "JOD 100+",
        maxStay: "1–2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "police_clearance", "medical_report",
        ]),
      },
    ],
  },

  // ─── MALAYSIA ───────────────────────────────────────────────────────────────
  {
    countryCode: "MY",
    countryName: "Malaysia",
    flag: "🇲🇾",
    continent: "Asia",
    capital: "Kuala Lumpur",
    currency: "MYR",
    visaTypes: [
      {
        id: "tourist",
        label: "eNTRI / eVisa (Tourist)",
        description: "Electronic travel authorization for tourism. Valid for a single entry.",
        icon: "luggage",
        processingTime: "1–3 days",
        governmentFee: "MYR 50",
        maxStay: "30 days",
        validity: "3 months from issuance",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "employment_letter",
        ]),
      },
      {
        id: "student",
        label: "Student Pass",
        description: "For full-time study at a Malaysian institution of higher learning.",
        icon: "school",
        processingTime: "4–8 weeks",
        governmentFee: "MYR 500–1,000",
        maxStay: "Duration of study",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "university_acceptance", "bank_statement",
          "english_proficiency", "university_transcripts",
          "medical_report",
        ]),
      },
    ],
  },

  // ─── SINGAPORE ──────────────────────────────────────────────────────────────
  {
    countryCode: "SG",
    countryName: "Singapore",
    flag: "🇸🇬",
    continent: "Asia",
    capital: "Singapore",
    currency: "SGD",
    embassyUrl: "https://www.mfa.gov.sg",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist / Short-Term Visit Pass",
        description: "For tourism or business visits to Singapore.",
        icon: "luggage",
        processingTime: "3–5 business days",
        governmentFee: "SGD 30",
        maxStay: "30 days",
        validity: "Per approval",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "employment_letter",
          "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "employment_pass",
        label: "Employment Pass (EP)",
        description: "For foreign professionals, managers, and executives working in Singapore.",
        icon: "work",
        processingTime: "3 weeks",
        governmentFee: "SGD 105",
        maxStay: "1–2 years (renewable)",
        validity: "Per approval",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "university_transcripts", "police_clearance",
        ]),
      },
    ],
  },

  // ─── SOUTH KOREA ────────────────────────────────────────────────────────────
  {
    countryCode: "KR",
    countryName: "South Korea",
    flag: "🇰🇷",
    continent: "Asia",
    capital: "Seoul",
    currency: "KRW",
    embassyUrl: "https://overseas.mofa.go.kr/eg-ar",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa (C-3)",
        description: "For short-term tourism, leisure, and visiting family in South Korea.",
        icon: "luggage",
        processingTime: "5 business days",
        governmentFee: "$60",
        maxStay: "90 days",
        validity: "Single / Multiple entry",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "employment_letter",
          "hotel_reservation", "return_ticket",
          "no_objection_certificate",
        ]),
      },
      {
        id: "student",
        label: "Student Visa (D-2)",
        description: "For studying at Korean universities or research institutions.",
        icon: "school",
        processingTime: "3–5 business days",
        governmentFee: "$60",
        maxStay: "Duration of study",
        validity: "Per enrollment",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "university_acceptance", "bank_statement",
          "university_transcripts", "english_proficiency",
          "no_objection_certificate",
        ]),
      },
      {
        id: "work",
        label: "Employment Visa (E series)",
        description: "Various work visas: E-1 (professor), E-2 (language instructor), E-7 (specialty occupation), etc.",
        icon: "work",
        processingTime: "2–4 weeks",
        governmentFee: "$60",
        maxStay: "1–2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "work_contract", "employment_letter",
          "university_transcripts", "police_clearance",
        ]),
      },
    ],
  },

  // ─── RUSSIA ─────────────────────────────────────────────────────────────────
  {
    countryCode: "RU",
    countryName: "Russia",
    flag: "🇷🇺",
    continent: "Europe",
    capital: "Moscow",
    currency: "RUB",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa",
        description: "For tourism and sightseeing in Russia. Requires a tourist voucher from an accredited Russian travel company.",
        icon: "luggage",
        processingTime: "5–10 business days",
        governmentFee: "$50–$160 (single/double/multiple)",
        maxStay: "30 days",
        validity: "Per booking",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "hotel_reservation", "invitation_letter",
          "travel_insurance",
        ]),
      },
      {
        id: "business",
        label: "Business Visa",
        description: "For business meetings and commercial activities in Russia.",
        icon: "business_center",
        processingTime: "5–10 business days",
        governmentFee: "$50–$160",
        maxStay: "Up to 1 year",
        validity: "Single / Multiple",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "business_letter", "invitation_letter",
          "company_registration", "travel_insurance",
        ]),
      },
    ],
  },

  // ─── EGYPT ──────────────────────────────────────────────────────────────────
  {
    countryCode: "EG",
    countryName: "Egypt",
    flag: "🇪🇬",
    continent: "Africa",
    capital: "Cairo",
    currency: "EGP",
    visaFreeForEgyptian: true,
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa (e-Visa)",
        description: "Single entry e-visa for foreign nationals wishing to visit Egypt. Also available on arrival.",
        icon: "luggage",
        processingTime: "3–7 business days (online)",
        governmentFee: "$25",
        maxStay: "30 days",
        validity: "Per entry",
        eVisa: true,
        visaOnArrival: true,
        requiredDocuments: docs([
          "passport", "photo", "bank_statement",
          "hotel_reservation", "return_ticket",
        ]),
      },
    ],
  },

  // ─── MOROCCO ────────────────────────────────────────────────────────────────
  {
    countryCode: "MA",
    countryName: "Morocco",
    flag: "🇲🇦",
    continent: "Africa",
    capital: "Rabat",
    currency: "MAD",
    visaFreeForEgyptian: false,
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa",
        description: "For tourism and leisure visits to Morocco.",
        icon: "luggage",
        processingTime: "5–10 business days",
        governmentFee: "MAD 200",
        maxStay: "90 days",
        validity: "Single entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "hotel_reservation", "return_ticket",
          "employment_letter", "travel_insurance",
        ]),
      },
    ],
  },

  // ─── NIGERIA ────────────────────────────────────────────────────────────────
  {
    countryCode: "NG",
    countryName: "Nigeria",
    flag: "🇳🇬",
    continent: "Africa",
    capital: "Abuja",
    currency: "NGN",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist / Business Visa",
        description: "For short visits to Nigeria for tourism or business activities.",
        icon: "luggage",
        processingTime: "3–5 business days",
        governmentFee: "$100",
        maxStay: "30 days",
        validity: "Single entry",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "invitation_letter", "employment_letter",
        ]),
      },
    ],
  },

  // ─── KENYA ──────────────────────────────────────────────────────────────────
  {
    countryCode: "KE",
    countryName: "Kenya",
    flag: "🇰🇪",
    continent: "Africa",
    capital: "Nairobi",
    currency: "KES",
    visaTypes: [
      {
        id: "e_tourist",
        label: "e-Visa (Tourist / Business)",
        description: "Single or multiple entry e-visa for tourism, business, or transit.",
        icon: "luggage",
        processingTime: "72 hours",
        governmentFee: "$51 (single) / $101 (multiple)",
        maxStay: "90 days per entry",
        validity: "Per approval",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "yellow_fever",
        ].filter(id => id in DOCUMENT_REGISTRY)).concat(docs(["vaccination_certificate"])),
      },
    ],
  },

  // ─── BRAZIL ─────────────────────────────────────────────────────────────────
  {
    countryCode: "BR",
    countryName: "Brazil",
    flag: "🇧🇷",
    continent: "South America",
    capital: "Brasília",
    currency: "BRL",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa / eVisa",
        description: "For tourism and leisure visits to Brazil.",
        icon: "luggage",
        processingTime: "72 hours (e-Visa)",
        governmentFee: "$80",
        maxStay: "90 days",
        validity: "Per approval",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "employment_letter", "travel_insurance",
        ]),
      },
      {
        id: "business",
        label: "Business Visa (VITEM II)",
        description: "For business meetings, conferences, and commercial activities.",
        icon: "business_center",
        processingTime: "3–5 business days",
        governmentFee: "$160",
        maxStay: "90 days",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "business_letter", "invitation_letter",
          "company_registration", "employment_letter",
        ]),
      },
    ],
  },

  // ─── NEW ZEALAND ─────────────────────────────────────────────────────────────
  {
    countryCode: "NZ",
    countryName: "New Zealand",
    flag: "🇳🇿",
    continent: "Oceania",
    capital: "Wellington",
    currency: "NZD",
    embassyUrl: "https://www.immigration.govt.nz",
    visaTypes: [
      {
        id: "visitor",
        label: "Visitor Visa",
        description: "For tourism, visiting family, or business activities in New Zealand.",
        icon: "luggage",
        processingTime: "20–30 days",
        governmentFee: "NZD 211",
        maxStay: "Up to 9 months",
        validity: "Multiple entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "employment_letter",
          "hotel_reservation", "return_ticket",
          "travel_insurance", "no_objection_certificate",
        ]),
      },
      {
        id: "student",
        label: "Student Visa",
        description: "For full-time study at a New Zealand educational provider.",
        icon: "school",
        processingTime: "4–8 weeks",
        governmentFee: "NZD 330",
        maxStay: "Duration of study",
        validity: "Per course",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "university_acceptance", "bank_statement",
          "english_proficiency", "university_transcripts",
          "medical_report", "police_clearance",
        ]),
      },
    ],
  },

  // ─── SOUTH AFRICA ───────────────────────────────────────────────────────────
  {
    countryCode: "ZA",
    countryName: "South Africa",
    flag: "🇿🇦",
    continent: "Africa",
    capital: "Pretoria",
    currency: "ZAR",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist Visa",
        description: "For tourism and leisure in South Africa.",
        icon: "luggage",
        processingTime: "5–10 business days",
        governmentFee: "ZAR 425",
        maxStay: "30 days",
        validity: "Single entry",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo", "application_form",
          "bank_statement", "hotel_reservation", "return_ticket",
          "employment_letter", "travel_insurance",
          "vaccination_certificate", // Yellow fever if coming from endemic countries
        ]),
      },
    ],
  },

  // ─── BAHRAIN ────────────────────────────────────────────────────────────────
  {
    countryCode: "BH",
    countryName: "Bahrain",
    flag: "🇧🇭",
    continent: "Asia",
    capital: "Manama",
    currency: "BHD",
    visaTypes: [
      {
        id: "tourist",
        label: "Tourist e-Visa",
        description: "Online visa for tourism. Egyptians can get a visa on arrival.",
        icon: "luggage",
        processingTime: "Instant (online) / On arrival",
        governmentFee: "BHD 5",
        maxStay: "14 days (extendable)",
        validity: "Per entry",
        eVisa: true,
        visaOnArrival: true,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
        ]),
      },
      {
        id: "work",
        label: "Work Visa / CPR",
        description: "Employment visa for working in Bahrain, sponsored by employer.",
        icon: "work",
        processingTime: "2–4 weeks",
        governmentFee: "BHD 100+",
        maxStay: "2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts",
        ]),
      },
    ],
  },

  // ─── OMAN ───────────────────────────────────────────────────────────────────
  {
    countryCode: "OM",
    countryName: "Oman",
    flag: "🇴🇲",
    continent: "Asia",
    capital: "Muscat",
    currency: "OMR",
    visaTypes: [
      {
        id: "e_tourist",
        label: "e-Visa (Tourist)",
        description: "Online tourist visa for Oman. Multiple entry available.",
        icon: "luggage",
        processingTime: "1–3 business days",
        governmentFee: "OMR 20 (single) / OMR 50 (multiple)",
        maxStay: "30 days per entry",
        validity: "1 year",
        eVisa: true,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "bank_statement", "return_ticket", "hotel_reservation",
          "employment_letter",
        ]),
      },
      {
        id: "work",
        label: "Work Visa / Residence Card",
        description: "Employment visa for working in Oman. Sponsored by employer.",
        icon: "work",
        processingTime: "3–6 weeks",
        governmentFee: "OMR 100+",
        maxStay: "2 years (renewable)",
        validity: "Per contract",
        eVisa: false,
        visaOnArrival: false,
        requiredDocuments: docs([
          "passport", "passport_copy", "photo",
          "work_contract", "employment_letter",
          "medical_report", "police_clearance",
          "university_transcripts",
        ]),
      },
    ],
  },
];

// ─── Lookup Helpers ───────────────────────────────────────────────────────────

/** Find a country by ISO code */
export function getCountryByCode(code: string): CountryVisaProfile | undefined {
  return VISA_DATABASE.find((c) => c.countryCode === code);
}

/** Find a visa type within a country */
export function getVisaType(countryCode: string, visaTypeId: string): VisaType | undefined {
  return getCountryByCode(countryCode)?.visaTypes.find((v) => v.id === visaTypeId);
}

/** Get all countries as summaries (for country selector grid) */
export function getAllCountrySummaries() {
  return VISA_DATABASE.map((c) => ({
    countryCode: c.countryCode,
    countryName: c.countryName,
    flag: c.flag,
    continent: c.continent,
    capital: c.capital,
    currency: c.currency,
    visaFreeForEgyptian: c.visaFreeForEgyptian ?? false,
    embassyUrl: c.embassyUrl,
    visaTypeCount: c.visaTypes.length,
    visaTypeIds: c.visaTypes.map((v) => v.id),
    visaTypeLabels: c.visaTypes.map((v) => v.label),
    eVisa: c.visaTypes.some((v) => v.eVisa),
    visaOnArrival: c.visaTypes.some((v) => v.visaOnArrival),
    processingTime: c.visaTypes[0]?.processingTime ?? "Varies",
  }));
}
